doc: add docs about ts configuration file
web-infra-dev/rspack-website pull request #238
Opened 2023-03-16 20:24 UTC by HerringtonDarkholme

2023-03-17 06:04 UTC, h-a-n-a commented on docs/en/config/index.mdx
> +import { RspackOptions } from '@rspack/core'
Since many users viewing this may follow the quick start guide with the built-in rspack-cli. I might suggest to change this type to cli
```suggestion
import { RspackOptions } from '@rspack/cli'
```

2023-03-17 06:05 UTC, h-a-n-a commented on docs/zh/config/index.mdx
> +import { RspackOptions } from '@rspack/core'
```suggestion
import { RspackOptions } from '@rspack/cli'
```

2023-03-17 06:08 UTC, fwqaaq requested changes
Some suggestions

2023-03-17 06:08 UTC, fwqaaq commented on docs/zh/config/index.mdx
> +你需要把`ts-node`安装为`devDependencies`，这样rspack才能解析`ts`扩展。
```suggestion
你需要把 `ts-node` 安装为 `devDependencies`，这样 rspack 才能解析 `ts` 扩展。
```

2023-03-17 06:08 UTC, fwqaaq commented on docs/zh/config/index.mdx
> +注意，如果JS文件不存在，rspack将首先搜索JavaScript，然后才是TypeScript。
```suggestion
注意，如果 JS 文件不存在，rspack 将首先搜索 JavaScript，然后才是 TypeScript。
```

2023-03-17 06:08 UTC, fwqaaq commented on docs/zh/config/index.mdx
> +另外，你也可以使用TypeScript作为配置文件。默认的TypeScript配置文件名称是`rspack.config.ts`。
```suggestion
另外，你也可以使用 TypeScript 作为配置文件。默认的 TypeScript 配置文件名称是 `rspack.config.ts`。
```

2023-03-17 13:14 UTC, HerringtonDarkholme commented on docs/zh/config/index.mdx
> +import { RspackOptions } from '@rspack/core'
ditto

2023-03-17 13:33 UTC, HerringtonDarkholme commented on docs/en/config/index.mdx
> +import { RspackOptions } from '@rspack/core'
I changed it to Configuration from rspack/cli

2023-03-18 05:46 UTC, h-a-n-a approved these changes

2023-03-18 05:47 UTC, merged

2023-03-18 05:47 UTC, h-a-n-a commented
Thank you!